#!/usr/bin/perl -w

use strict;

#./ykpersonalize -1 -ofixed=
my $YKI_BIN = '/usr/local/src/yubikey-personalization/ykinfo';
my $YKP_BIN = '/usr/local/src/yubikey-personalization/ykpersonalize';

sub accept_input {
	my $input = <STDIN>;
	chomp $input;
	return $input;
}

#print "Short press the YubiKey now: ";
#my $token = accept_input();

#my $public_id = substr($token, 0, 12);
my $public_id = `modhex -h \$(openssl rand -hex 6)`;
chomp $public_id;
my $aes_key = lc(`openssl enc -aes-128-cbc -k \$(openssl rand -base64 32) -nosalt -P|grep key=|tr -d 'key='`);
chomp $aes_key;
my $serial = `$YKI_BIN -s | grep -o -P '(\\d+)'`;
chomp $serial;
my $private_id = '0' x 12;

print "serial: $serial\n";
print "public id: $public_id\n";
print "private_id: $private_id\n";
print "aes key: $aes_key\n";
#print "token: $token\n";

my $out = `$YKP_BIN -d -y -1 -a$aes_key -ouid=$private_id -ofixed=$public_id -oserial-api-visible`;
